services:
  app:
    build:
      context: .
      dockerfile: ex_26_Dockerfile 
    container_name: my-flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: always
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

